/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Alerta.Alerta;
import static Aplicacion.PruebaInterfazTienda.cargaArregloUsuarios;
import Modelo.Login;
import Modelo.Usuarios.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 4PF42LA_RS6
 */
public class InterfazGraficaTienda extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGraficaTienda
     */
    FondoPanel fondo = new FondoPanel();
    public InterfazGraficaTienda() {
        this.setContentPane(fondo);
        setIconImage(new ImageIcon(getClass().getResource("/Vista/Images/CarritoComprasLogo.png")).getImage());
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        UserTxt = new javax.swing.JTextField();
        PanelLine2 = new javax.swing.JPanel();
        PanelLine1 = new javax.swing.JPanel();
        LabelLoginTitle = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JPasswordField();
        AccesPanelButton = new javax.swing.JPanel();
        AccessLabel = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de administración de tiendas");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordLabel.setBackground(new java.awt.Color(204, 204, 204));
        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(153, 153, 153));
        PasswordLabel.setText("Contraseña");
        BackgroundPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 22));

        UserLabel.setBackground(new java.awt.Color(204, 204, 204));
        UserLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(153, 153, 153));
        UserLabel.setText("Usuario");
        BackgroundPanel.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 23));

        UserTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UserTxt.setBorder(null);
        BackgroundPanel.add(UserTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 248, 40));

        PanelLine2.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout PanelLine2Layout = new javax.swing.GroupLayout(PanelLine2);
        PanelLine2.setLayout(PanelLine2Layout);
        PanelLine2Layout.setHorizontalGroup(
            PanelLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        PanelLine2Layout.setVerticalGroup(
            PanelLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        BackgroundPanel.add(PanelLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 2));

        PanelLine1.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout PanelLine1Layout = new javax.swing.GroupLayout(PanelLine1);
        PanelLine1.setLayout(PanelLine1Layout);
        PanelLine1Layout.setHorizontalGroup(
            PanelLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        PanelLine1Layout.setVerticalGroup(
            PanelLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        BackgroundPanel.add(PanelLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, -1));

        LabelLoginTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelLoginTitle.setForeground(new java.awt.Color(51, 51, 51));
        LabelLoginTitle.setText("Iniciar sesión");
        BackgroundPanel.add(LabelLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        PasswordTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordTxt.setBorder(null);
        BackgroundPanel.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 248, 36));

        AccesPanelButton.setBackground(new java.awt.Color(204, 102, 0));
        AccesPanelButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AccesPanelButtonMouseMoved(evt);
            }
        });
        AccesPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccesPanelButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccesPanelButtonMouseExited(evt);
            }
        });
        AccesPanelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccessLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AccessLabel.setForeground(new java.awt.Color(255, 255, 255));
        AccessLabel.setText("Acceder");
        AccesPanelButton.add(AccessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        BackgroundPanel.add(AccesPanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 120, 30));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/LoginLogo.png"))); // NOI18N
        BackgroundPanel.add(LogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 113, 330, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccesPanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccesPanelButtonMouseExited
        AccesPanelButton.setBackground(new Color(204,102,0));
    }//GEN-LAST:event_AccesPanelButtonMouseExited

    private void AccesPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccesPanelButtonMouseClicked
        String username = UserTxt.getText();
        String password = PasswordTxt.getText();
        Login NuevoLogin = new Login(username, password);
        verificaLogin(NuevoLogin);
    }//GEN-LAST:event_AccesPanelButtonMouseClicked

    private void AccesPanelButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccesPanelButtonMouseMoved
        AccesPanelButton.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_AccesPanelButtonMouseMoved

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccesPanelButton;
    private javax.swing.JLabel AccessLabel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel LabelLoginTitle;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel PanelLine1;
    private javax.swing.JPanel PanelLine2;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UserTxt;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen; 
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Vista/ImagenInterfaz.png")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    public void verificaLogin(Login intentoInicioSesion){
        ArrayList<Usuario> listaUsuarios = new ArrayList<>();
        listaUsuarios = cargaArregloUsuarios();
        boolean encontrado = false;
        int posicionUsuario = 0;
        for(int i = 0; i < listaUsuarios.size();i++){
            if(intentoInicioSesion.getUsername().equals(listaUsuarios.get(i).getUsername())){
                if(intentoInicioSesion.getPassword().equals(listaUsuarios.get(i).getPassword())){
                    encontrado = true;
                    posicionUsuario = i;
                }   
            }   
        }   
        if(encontrado){
            this.dispose();
            ejecutaMenuInicial(posicionUsuario);
        }
        else{
            new Alerta().setVisible(true);
        }
    }
    
    public void ejecutaMenuInicial(int posicionUsuario){
        MenuInicial MenuInicial = new MenuInicial();
        MenuInicial.setVisible(true);
        MenuInicial.configuraMenuDatos(posicionUsuario);
    }
    
}

