/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Aplicacion.PruebaInterfazTienda.cargaArregloUsuarios;
import Modelo.Usuarios.*;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author 4PF42LA_RS6
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        TitleLabel = new javax.swing.JLabel();
        TitleLogoLabel = new javax.swing.JLabel();
        MenuTitleLabel = new javax.swing.JLabel();
        PinkPanel = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        UserLogoLabel = new javax.swing.JLabel();
        JobLabel = new javax.swing.JLabel();
        ProfileLabel = new javax.swing.JLabel();
        ChargePanel = new javax.swing.JPanel();
        ChargeLabel = new javax.swing.JLabel();
        MoneyIcon = new javax.swing.JLabel();
        ConfigurationPanel = new javax.swing.JPanel();
        ConfigurationIcon = new javax.swing.JLabel();
        ConfigurationLabel = new javax.swing.JLabel();
        AdministrationPanel = new javax.swing.JPanel();
        AdministrationLabel = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        LogoutLabel = new javax.swing.JLabel();
        LogoutIcon = new javax.swing.JLabel();
        InventoryPanel = new javax.swing.JPanel();
        InventoryLabel = new javax.swing.JLabel();
        InventoryIcon = new javax.swing.JLabel();
        Tabs = new javax.swing.JTabbedPane();
        ChargeTab = new javax.swing.JPanel();
        AdministrationTab = new javax.swing.JPanel();
        InventoryTab = new javax.swing.JPanel();
        SettingsTab = new javax.swing.JPanel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Microsoft Yi Baiti", 2, 48)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("Sistema de administración de tiendas");
        getContentPane().add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 660, 110));

        TitleLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/CarritoComprasLogo.png"))); // NOI18N
        getContentPane().add(TitleLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 110));

        MenuTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/PanelRojo.png"))); // NOI18N
        getContentPane().add(MenuTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 110));

        PinkPanel.setBackground(new java.awt.Color(255, 185, 185));
        PinkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        PinkPanel.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 30));

        UserLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/ImagenUsuario.png"))); // NOI18N
        PinkPanel.add(UserLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 130));

        JobLabel.setBackground(new java.awt.Color(0, 0, 0));
        JobLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JobLabel.setForeground(new java.awt.Color(255, 255, 255));
        PinkPanel.add(JobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 30));

        ProfileLabel.setBackground(new java.awt.Color(255, 102, 102));
        ProfileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/PanelRojoRosa.png"))); // NOI18N
        ProfileLabel.setText("jLabel2");
        PinkPanel.add(ProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 290, 280));

        ChargePanel.setBackground(new java.awt.Color(189, 47, 47));
        ChargePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ChargePanelMouseMoved(evt);
            }
        });
        ChargePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChargePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChargePanelMouseExited(evt);
            }
        });

        ChargeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ChargeLabel.setForeground(new java.awt.Color(255, 255, 255));
        ChargeLabel.setText("Cobrar");

        MoneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/MenuImages/MoneyWLogo.png"))); // NOI18N

        javax.swing.GroupLayout ChargePanelLayout = new javax.swing.GroupLayout(ChargePanel);
        ChargePanel.setLayout(ChargePanelLayout);
        ChargePanelLayout.setHorizontalGroup(
            ChargePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChargePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(MoneyIcon)
                .addGap(18, 18, 18)
                .addComponent(ChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        ChargePanelLayout.setVerticalGroup(
            ChargePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MoneyIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(ChargeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PinkPanel.add(ChargePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 290, 70));

        ConfigurationPanel.setBackground(new java.awt.Color(255, 142, 142));
        ConfigurationPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ConfigurationPanelMouseMoved(evt);
            }
        });
        ConfigurationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfigurationPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfigurationPanelMouseExited(evt);
            }
        });

        ConfigurationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/MenuImages/ConfigurationLogo.png"))); // NOI18N

        ConfigurationLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ConfigurationLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfigurationLabel.setText("Configuraciones");

        javax.swing.GroupLayout ConfigurationPanelLayout = new javax.swing.GroupLayout(ConfigurationPanel);
        ConfigurationPanel.setLayout(ConfigurationPanelLayout);
        ConfigurationPanelLayout.setHorizontalGroup(
            ConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigurationPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(ConfigurationIcon)
                .addGap(18, 18, 18)
                .addComponent(ConfigurationLabel)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        ConfigurationPanelLayout.setVerticalGroup(
            ConfigurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfigurationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConfigurationIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        PinkPanel.add(ConfigurationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, 70));

        AdministrationPanel.setBackground(new java.awt.Color(236, 75, 75));
        AdministrationPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AdministrationPanelMouseMoved(evt);
            }
        });
        AdministrationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministrationPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdministrationPanelMouseExited(evt);
            }
        });

        AdministrationLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AdministrationLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdministrationLabel.setText("Administrar");

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/MenuImages/UserLogo.png"))); // NOI18N

        javax.swing.GroupLayout AdministrationPanelLayout = new javax.swing.GroupLayout(AdministrationPanel);
        AdministrationPanel.setLayout(AdministrationPanelLayout);
        AdministrationPanelLayout.setHorizontalGroup(
            AdministrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministrationPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(UserIcon)
                .addGap(18, 18, 18)
                .addComponent(AdministrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        AdministrationPanelLayout.setVerticalGroup(
            AdministrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdministrationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        PinkPanel.add(AdministrationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 290, 70));

        LogoutPanel.setBackground(new java.awt.Color(255, 81, 81));
        LogoutPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseMoved(evt);
            }
        });
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseExited(evt);
            }
        });

        LogoutLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutLabel.setText("Cerrar sesión");

        LogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/MenuImages/LogoutLogo.png"))); // NOI18N

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(LogoutIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(LogoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PinkPanel.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 290, 70));

        InventoryPanel.setBackground(new java.awt.Color(255, 81, 81));
        InventoryPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InventoryPanelMouseMoved(evt);
            }
        });
        InventoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryPanelMouseExited(evt);
            }
        });

        InventoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        InventoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        InventoryLabel.setText("Inventario");

        InventoryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/MenuImages/InventoryLogo.png"))); // NOI18N

        javax.swing.GroupLayout InventoryPanelLayout = new javax.swing.GroupLayout(InventoryPanel);
        InventoryPanel.setLayout(InventoryPanelLayout);
        InventoryPanelLayout.setHorizontalGroup(
            InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(InventoryIcon)
                .addGap(18, 18, 18)
                .addComponent(InventoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        InventoryPanelLayout.setVerticalGroup(
            InventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InventoryIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(InventoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PinkPanel.add(InventoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 290, 70));

        getContentPane().add(PinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 290, 730));

        ChargeTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ChargeTabLayout = new javax.swing.GroupLayout(ChargeTab);
        ChargeTab.setLayout(ChargeTabLayout);
        ChargeTabLayout.setHorizontalGroup(
            ChargeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        ChargeTabLayout.setVerticalGroup(
            ChargeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        Tabs.addTab("Cobrar", ChargeTab);

        AdministrationTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout AdministrationTabLayout = new javax.swing.GroupLayout(AdministrationTab);
        AdministrationTab.setLayout(AdministrationTabLayout);
        AdministrationTabLayout.setHorizontalGroup(
            AdministrationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        AdministrationTabLayout.setVerticalGroup(
            AdministrationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        Tabs.addTab("Administrar", AdministrationTab);

        InventoryTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout InventoryTabLayout = new javax.swing.GroupLayout(InventoryTab);
        InventoryTab.setLayout(InventoryTabLayout);
        InventoryTabLayout.setHorizontalGroup(
            InventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        InventoryTabLayout.setVerticalGroup(
            InventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        Tabs.addTab("Inventario", InventoryTab);

        SettingsTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SettingsTabLayout = new javax.swing.GroupLayout(SettingsTab);
        SettingsTab.setLayout(SettingsTabLayout);
        SettingsTabLayout.setHorizontalGroup(
            SettingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        SettingsTabLayout.setVerticalGroup(
            SettingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        Tabs.addTab("Configuraciones", SettingsTab);

        getContentPane().add(Tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 910, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChargePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChargePanelMouseMoved
        ChargePanel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_ChargePanelMouseMoved

    private void ChargePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChargePanelMouseExited
        ChargePanel.setBackground(new Color(189,47,47));
    }//GEN-LAST:event_ChargePanelMouseExited

    private void AdministrationPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrationPanelMouseMoved
        AdministrationPanel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_AdministrationPanelMouseMoved

    private void AdministrationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrationPanelMouseExited
        AdministrationPanel.setBackground(new Color(236,75,75));
    }//GEN-LAST:event_AdministrationPanelMouseExited

    private void InventoryPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryPanelMouseMoved
        InventoryPanel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_InventoryPanelMouseMoved

    private void InventoryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryPanelMouseExited
        InventoryPanel.setBackground(new Color(255,81,81));
    }//GEN-LAST:event_InventoryPanelMouseExited

    private void ConfigurationPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfigurationPanelMouseMoved
        ConfigurationPanel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_ConfigurationPanelMouseMoved

    private void ConfigurationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfigurationPanelMouseExited
        ConfigurationPanel.setBackground(new Color(255,142,142));
    }//GEN-LAST:event_ConfigurationPanelMouseExited

    private void LogoutPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseMoved
        LogoutPanel.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_LogoutPanelMouseMoved

    private void LogoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseExited
        LogoutPanel.setBackground(new Color(255,81,81));
    }//GEN-LAST:event_LogoutPanelMouseExited

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        this.dispose();
        new InterfazGraficaTienda().setVisible(true);
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void ChargePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChargePanelMouseClicked
        Tabs.setSelectedIndex(0);
    }//GEN-LAST:event_ChargePanelMouseClicked

    private void AdministrationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrationPanelMouseClicked
        Tabs.setSelectedIndex(1);
    }//GEN-LAST:event_AdministrationPanelMouseClicked

    private void InventoryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryPanelMouseClicked
        Tabs.setSelectedIndex(2);
    }//GEN-LAST:event_InventoryPanelMouseClicked

    private void ConfigurationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfigurationPanelMouseClicked
        Tabs.setSelectedIndex(3);
    }//GEN-LAST:event_ConfigurationPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministrationLabel;
    private javax.swing.JPanel AdministrationPanel;
    private javax.swing.JPanel AdministrationTab;
    private javax.swing.JLabel ChargeLabel;
    private javax.swing.JPanel ChargePanel;
    private javax.swing.JPanel ChargeTab;
    private javax.swing.JLabel ConfigurationIcon;
    private javax.swing.JLabel ConfigurationLabel;
    private javax.swing.JPanel ConfigurationPanel;
    private javax.swing.JLabel InventoryIcon;
    private javax.swing.JLabel InventoryLabel;
    private javax.swing.JPanel InventoryPanel;
    private javax.swing.JPanel InventoryTab;
    private javax.swing.JLabel JobLabel;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JLabel MenuTitleLabel;
    private javax.swing.JLabel MoneyIcon;
    private javax.swing.JPanel PinkPanel;
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JPanel SettingsTab;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel TitleLogoLabel;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UserLogoLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
    
    public void configuraMenuDatos(int posicionUsuario){
        ArrayList<Usuario> listaUsuarios = cargaArregloUsuarios();
        Usuario Usuario = (Usuario)listaUsuarios.get(posicionUsuario);
        String nombre = Usuario.getNombre() + " " + Usuario.getApellidoP() + " "  + Usuario.getApellidoM();
        cargaNombre(nombre);
        cargaPuesto(listaUsuarios, posicionUsuario);
        
    }
    public void cargaNombre(String nombre){
        UsernameLabel.setText(nombre);
        UsernameLabel.setHorizontalAlignment(0);
    }
    public void cargaPuesto(ArrayList<Usuario> listaUsuarios, int posicionUsuario){
        if(listaUsuarios.get(posicionUsuario) instanceof Gerente)
            JobLabel.setText("Gerente");
        if(listaUsuarios.get(posicionUsuario) instanceof Empleado)
            JobLabel.setText("Empleado");
        JobLabel.setHorizontalAlignment(0);
    }
    //Aquí van métodos de sus respectivas pestañas
    
}

