/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alerta;

import java.awt.Color;

/**
 *
 * @author 4PF42LA_RS6
 */
public class Alerta extends javax.swing.JFrame {

    /**
     * Creates new form Alerta
     */
    public Alerta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AlertLabel = new javax.swing.JLabel();
        AlertaIconLabel = new javax.swing.JLabel();
        AcceptPanel = new javax.swing.JPanel();
        AcceptLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        AlertLabel.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        AlertLabel.setText("Usuario o contraseña incorrectos, vuelva a intentar");

        AlertaIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/AlertaLogo.png"))); // NOI18N

        AcceptPanel.setBackground(new java.awt.Color(204, 102, 0));
        AcceptPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AcceptPanelMouseMoved(evt);
            }
        });
        AcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AcceptPanelMouseExited(evt);
            }
        });

        AcceptLabel.setBackground(new java.awt.Color(0, 0, 0));
        AcceptLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        AcceptLabel.setForeground(new java.awt.Color(255, 255, 255));
        AcceptLabel.setText("Aceptar");

        javax.swing.GroupLayout AcceptPanelLayout = new javax.swing.GroupLayout(AcceptPanel);
        AcceptPanel.setLayout(AcceptPanelLayout);
        AcceptPanelLayout.setHorizontalGroup(
            AcceptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcceptPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(AcceptLabel)
                .addGap(52, 52, 52))
        );
        AcceptPanelLayout.setVerticalGroup(
            AcceptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcceptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AcceptLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(AlertaIconLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AcceptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(AlertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(AlertaIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlertLabel)
                .addGap(29, 29, 29)
                .addComponent(AcceptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptPanelMouseClicked
        this.dispose();
    }//GEN-LAST:event_AcceptPanelMouseClicked

    private void AcceptPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptPanelMouseMoved
        AcceptPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_AcceptPanelMouseMoved

    private void AcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptPanelMouseExited
        AcceptPanel.setBackground(new Color(204,102,0));
    }//GEN-LAST:event_AcceptPanelMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcceptLabel;
    private javax.swing.JPanel AcceptPanel;
    private javax.swing.JLabel AlertLabel;
    private javax.swing.JLabel AlertaIconLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
