/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alerta;

import java.awt.Color;

/**
 *
 * @author 4PF42LA_RS6
 */
public class AlertaMenu extends javax.swing.JDialog {

    /**
     * Creates new form AlertaMenu
     * @param parent
     * @param modal
     */
    public AlertaMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AlertLabel.setHorizontalAlignment(0);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        AlertaIconLabel = new javax.swing.JLabel();
        AcceptPanel = new javax.swing.JPanel();
        AcceptLabel = new javax.swing.JLabel();
        AlertLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error");
        setIconImage(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));

        AlertaIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/AlertaLogo.png"))); // NOI18N

        AcceptPanel.setBackground(new java.awt.Color(204, 102, 0));
        AcceptPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AcceptPanelMouseMoved(evt);
            }
        });
        AcceptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AcceptPanelMouseExited(evt);
            }
        });

        AcceptLabel.setBackground(new java.awt.Color(0, 0, 0));
        AcceptLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        AcceptLabel.setForeground(new java.awt.Color(255, 255, 255));
        AcceptLabel.setText("Aceptar");

        javax.swing.GroupLayout AcceptPanelLayout = new javax.swing.GroupLayout(AcceptPanel);
        AcceptPanel.setLayout(AcceptPanelLayout);
        AcceptPanelLayout.setHorizontalGroup(
            AcceptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcceptPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(AcceptLabel)
                .addGap(52, 52, 52))
        );
        AcceptPanelLayout.setVerticalGroup(
            AcceptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcceptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AcceptLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AlertLabel.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        AlertLabel.setText("Usuario o contraseña incorrectos, vuelva a intentar");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(AcceptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AlertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(AlertaIconLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AlertaIconLabel)
                .addGap(18, 18, 18)
                .addComponent(AlertLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(AcceptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptPanelMouseMoved
        AcceptPanel.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_AcceptPanelMouseMoved

    private void AcceptPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptPanelMouseClicked
        this.dispose();
    }//GEN-LAST:event_AcceptPanelMouseClicked

    private void AcceptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptPanelMouseExited
        AcceptPanel.setBackground(new Color(204,102,0));
    }//GEN-LAST:event_AcceptPanelMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcceptLabel;
    private javax.swing.JPanel AcceptPanel;
    private javax.swing.JLabel AlertLabel;
    private javax.swing.JLabel AlertaIconLabel;
    private javax.swing.JPanel Background;
    // End of variables declaration//GEN-END:variables
}
